language: php
php:
  - 7.0
  - 7.1

install: composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.dist.xml --coverage-clover build/logs/clover.xml